name: mad_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase (compatible versions)
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  shared_preferences: ^2.3.2

  # UI + Fonts
  google_fonts: ^6.3.1
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"



flutter:
  uses-material-design: true

  # âœ… All images for your project
  assets:
    - assets/images/
